[package]
name = "redumps"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
sonic-rs = "0.5.6"

[profile.release]
# lto = true
opt-level = 3

[profile.profiling]
inherits = "release"
debug = true
